### ISSUE TITLE
Cannot compile from source on RHEL7 after #305 -- codecvt missing

### ISSUE THREAD

**Issue by jkrauska** [MisterTea/EternalTerminal#335]
I'm forced to use stock GCC in RHEL7.
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

When trying to compile, I get this error:

```
Headers.hpp:61:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
```

I've found a few notes saying I need gcc > 5 to support codecvt.

Are there any workarounds for this build issue?

**Comment by jkrauska** [comment]
This appears to have been introduced in #305
