### ISSUE TITLE
Failure to build with Mac Sonoma 14.7

### ISSUE THREAD

**Issue by mattgodbolt** [MisterTea/EternalTerminal#664]
When trying to install with `brew` on Sonoma 14.7:

```
==> Installing et from mistertea/et
==> cmake . -DDISABLE_VCPKG:BOOL=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
==> make install
Last 15 lines from /Users/mgodbolt/Library/Logs/Homebrew/et/02.make:
/tmp/et-20241022-97876-5tiujl/EternalTerminal-et-v6.2.9/external_imported/sentry-native/external/crashpad/minidump/minidump_misc_info_writer.cc:194:47: error: use of undeclared identifier '__MAC_OS_X_VERSION_MAX_ALLOWED'
  194 |       AvailabilityVersionToMacOSVersionNumber(__MAC_OS_X_VERSION_MAX_ALLOWED));
      |                                               ^
1 error generated.
```

I've tried reinstalling the latest developer tools (at least I think I have) as I saw other reports that looked a little similar, but this doesn't seem to be missing header files. Any help welcomed. Thank you!

**Comment by MisterTea** [comment]
Can you try this solution and let us know if you can compile with it:
https://stackoverflow.com/a/44340246

**Comment by mattgodbolt** [comment]
Hi: I'll give it a go but presumably that means I can't use `brew` and I'll need to check out this repo and try building directly from it. Will give that a go (unfortunately I'm a total mac noob, it's a dumb terminal to get me to Linux :D )

**Comment by mattgodbolt** [comment]
Actually there's nowhere for me to put this, and it seems like it's a vcpkg issue? I can't see how to edit a CMake cache variable that'll be picked up by a build that vcpkg is seemingly doing behind my back?

**Comment by mattgodbolt** [comment]
Created https://github.com/microsoft/vcpkg/issues/41756 - thanks again for the help so far.

**Comment by MisterTea** [comment]
Makes sense, best of luck!

**Comment by MisterTea** [comment]
@mattgodbolt according to the issue you linked, they fixed it in the latest version, which we should be on now. Can you try again?

**Comment by mattgodbolt** [comment]
@MisterTea I wish I could but I've moved jobs since and no longer have a mac! Sorry
